cache: ccache
language: c++
sudo: required
matrix:
  include:
    - os: osx
      osx_image: xcode 8.3
      compiler: clang
      addons:
        homebrew:
          packages:
           - opencv
           - ccache
          update: true
      env:
        - CC=clang++
      install:
        - export PATH="/usr/local/opt/ccache/libexec:$PATH"
      script:
       - make
    - os: linux
      dist: bionic
      compiler: gcc-8
      before_install:
        - sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        - sudo apt-get update
        - sudo apt-get install gcc-8 g++-8
        - g++-8 --version
        - sudo apt-get install libopencv-dev pkg-config
      env:
        - CC=g++-8
      script:
        - make
      after_success:
       - export CODECOV_TOKEN="619baaa1-1d7b-474e-9409-8b490f3e148f"
       - gcov *.cpp
       - bash <(curl -s https://codecov.io/bash)
