cache: ccache
language: c++
matrix:
  include:
    - os: osx
      osx_image: xcode 8.3
      compiler: clang
      addons:
        homebrew:
          packages:
           - opencv
           - ccache
          update: true
      env:
        - CC=clang++
      install:
        - export PATH="/usr/local/opt/ccache/libexec:$PATH"
      script:
       - make
    - os: linux
      dist: bionic
      sudo: required
      compiler: gcc-8
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - libopencv-dev
            - pkg-config
      env:
        - CC=gcc-8
      script:
        - make
      after_success:
       - export CODECOV_TOKEN="619baaa1-1d7b-474e-9409-8b490f3e148f"
       - gcov *.cpp
       - bash <(curl -s https://codecov.io/bash)
