cache: ccache
language: c++
sudo: required
matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      compiler: clang++
      addons:
        homebrew:
          packages:
           - opencv
           - ccache
          update: true
      install:
        - export PATH="/usr/local/opt/ccache/libexec:$PATH"
      script:
       - make
    - os: linux
      dist: bionic
      compiler: g++-8
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y gcc-8 g++-8
        - g++-8 --version
        - sudo apt-get install -y libopencv-dev pkg-config
      script:
        - make CXX=g++-8
      after_success:
       - export CODECOV_TOKEN="619baaa1-1d7b-474e-9409-8b490f3e148f"
       - gcov *.cpp
       - bash <(curl -s https://codecov.io/bash)
